from pathlib import Path
import json,hashlib,datetime,re,html
ROOT=Path('/Users/rocket/Desktop/HKUST IT/ip-/geometry-world-modeling')
D=ROOT/'work/S38_paper_learning/agent_b_geometry'; P=D/'primary'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def utc():return datetime.datetime.now(datetime.timezone.utc).isoformat()
recorded=utc()
records=[]
for f in ['retrieval_receipt.json','retrieval_fallback_receipt.json','memory_cvpr_retrieval.json','venue_retrieval_receipt.json']:
 obj=json.loads((P/f).read_text()); records.extend(obj if isinstance(obj,list) else [obj])
def paper(id,title,authors,venue,year,sections,axes,limits):
 h=(P/(id+'_venue.html')).read_text()
 if 'ICLR' in venue:
  assert title in h and 'International Conference on Learning Representations 2025' in h
 else:
  m=re.search(r'<meta name="citation_title" content="([^"]+)"',h)
  assert m and html.unescape(m.group(1))==title
  assert re.search(r'citation_publication_date" content="'+str(year),h)
 urls=[r['url'] for r in records if (r.get('id')==id+'_venue' or r.get('id')==id) and r.get('returncode',0)==0 and r.get('sha256')]
 pdf=(P/(id+'.pdf'))
 return {'id':id,'title':title,'authors':authors,'venue':venue,'year':year,'formal_proceedings_verified':True,'venue_evidence_file':str(P/(id+'_venue.html')),'venue_evidence_sha256':sha(P/(id+'_venue.html')),'primary_pdf':str(pdf),'pdf_sha256':sha(pdf),'primary_text':str(P/(id+'.txt')),'text_sha256':sha(P/(id+'.txt')),'read_scope':sections,'not_read':'Not a full supplemental/code/reproduction audit; unrelated results and full references not systematically reviewed.','four_axes':axes,'transfer_failure_notes':limits}
papers=[
 paper('vggsfm','VGGSfM: Visual Geometry Grounded Deep Structure From Motion',['Jianyuan Wang','Nikita Karaev','Christian Rupprecht','David Novotny'],'CVPR',2024,['Introduction pp.21687–21688','Sections 3.1–3.5 pp.21688–21691','Section4.2/4.3, Tables3–5 p.21693; joint-training comparison paragraph'],{'object':'tracks/cameras/3D points','mechanism':'joint differentiable tracking, initialization, triangulation, BA','input_granularity':'unordered multiview image set','setting':'static SfM; not strict causal stream'},['Swapped matching control retains own camera initialization.','Additional input/compute and training are not free when transferred.']),
 paper('monst3r','MonST3R: A Simple Approach for Estimating Geometry in the Presence of Motion',['Junyi Zhang','Charles Herrmann','Junhwa Hur','Varun Jampani','Trevor Darrell','Forrester Cole','Deqing Sun','Ming-Hsuan Yang'],'ICLR',2025,['Introduction/Fig2 failure explanation (also author arXiv v2 read)','Sections3.1–3.4 pp.4–7, equations1–7','Section4.1 setup; Section4.3 protocol also read in arXiv v2; Section4.5/Table5 pp.9–10'],{'object':'per-timestep dynamic pointmaps and camera parameters','mechanism':'dynamic-domain decoder/head finetuning, alignment plus static-masked flow and camera smoothness','input_granularity':'image pair/window video graph','setting':'dynamic monocular reconstruction; not test-time model finetuning'},['Dynamics and generator inconsistency cannot be equated.','A pose benefit does not imply depth or generated-video benefit.','Official conference PDF became available after HTML author-version fallback; final method facts checked in the conference PDF.']),
 paper('slam3r','SLAM3R: Real-Time Dense Scene Reconstruction from Monocular RGB Videos',['Yuzheng Liu','Siyan Dong','Shuzhe Wang','Yingda Yin','Yanchao Yang','Qingnan Fan','Baoquan Chen'],'CVPR',2025,['Sections2/3 overview pp.16652–16653','Sections3.1/3.2 pp.16653–16655','Section4 implementation/comparisons/analyses, Tables1–5 pp.16656–16658','Section5 limitations p.16658'],{'object':'local and world pointmaps','mechanism':'multiview I2P and learned L2W with bounded reservoir reference retrieval','input_granularity':'sliding windows and historical registered frames','setting':'static reconstruction; centered window uses future relative to keyframe'},['Cameras derived from predicted points can remain worse than pose-specialized SLAM.','Compare NoConf and matched view count; future access differs from strict online.']),
 paper('memory_adapters','Memory-based Adapters for Online 3D Scene Perception',['Xiuwei Xu','Chong Xia','Ziwei Wang','Linqing Zhao','Yueqi Duan','Jie Zhou','Jiwen Lu'],'CVPR',2024,['Introduction p.21605','Sections3.1–3.4 pp.21606–21608, equations1–7','Section4.1 setup and online benchmark protocol pp.21609–21610','Section4.3/Tables3–5 pp.21610–21611'],{'object':'image and point-cloud perception features','mechanism':'queued voxel max aggregation, residual adapters, channel memory, 3D-to-2D context','input_granularity':'posed RGB-D streaming frames','setting':'supervised offline adapter training followed by online detection/segmentation inference'},['Aligned RGB-D is stronger input than generated monocular observations.','A geometric projection error could poison features; frozen-backbone control is essential.'])
]
# Save actual URL identities from durable retrieval records, separately from summaries.
for p in papers:
 p['venue_url']=next(r['url'] for r in records if r.get('id')==p['id']+'_venue' and r.get('sha256'))
 matches=[r for r in records if r.get('sha256')==p['pdf_sha256']]
 p['pdf_url']=matches[0]['url']; p['access_started_utc']=matches[0]['started_utc'];p['access_completed_utc']=matches[0]['ended_utc']
source={
 'schema':'s38-paper-learning-agent-b-v1','recorded_utc':recorded,'research_scope':'Four selected formal 2024/2025 conference papers within requested 2023–2026 range; method-learning exercise, not an exhaustive survey or current-SOTA certification.',
 'papers':papers,
 'search':{
  'discovery_queries':['site:openaccess.thecvf.com VGGSfM Visual Geometry Grounded Deep Structure From Motion CVPR 2024','site:openreview.net MonST3R dynamic geometry ICLR 2025','site:openaccess.thecvf.com SLAM3R CVPR 2025','site:ecva.net LoopSplat ECCV 2024','"Memory-based Adapters for Online 3D Scene Perception"'],
  'discovery_timestamps':'Exact initial web-call UTC was not separately recorded; do not infer from this receipt. Durable primary downloads below have actual timestamps.',
  'mechanism_keyword_groups':[{'group':'mechanism+memory+domain','query':'"view dependent uncertainty" "memory" "3D" reconstruction'},{'group':'mechanism+consumer','query':'"uncertainty" "view selection" "geometry" "generation"'},{'group':'state-conflict+recency','query':'"memory" "3D" "conflicting" "2026"'}],
  'mechanism_domains':['openaccess.thecvf.com','proceedings.iclr.cc','openreview.net'],'mechanism_query_time':'Executed after 2026-09-07T03:17:18Z and before 03:19:01Z; exact tool-call wall clock not separately recorded.',
  '2026_scope_guard':[{'url':'https://openaccess.thecvf.com/content/CVPR2026/html/Shan_NI-Tex_Non-isometric_Image-based_Garment_Texture_Generation_CVPR_2026_paper.html','title':'NI-Tex: Non-isometric Image-based Garment Texture Generation','status':'official metadata/search result surfaced; not a fifth deeply read paper; no numerical/method claims imported'},{'url':'https://openaccess.thecvf.com/content/CVPR2026/papers/Xu_AREA3D_Active_Reconstruction_Agent_with_Unified_Feed-Forward_3D_Perception_and_CVPR_2026_paper.pdf','title':'AREA3D: Active Reconstruction Agent with Unified Feed-Forward 3D Perception and Vision-Language Guidance','status':'primary search result surfaced; follow-up novelty obstacle only, not fully read or accepted as a tested baseline here'},{'url':'https://openreview.net/pdf/13b03447437f26eb7486b075a3920a89a1f7a9e9.pdf','status':'search result states published ICLR2026 and uncertainty viewpoint selection; title and formal decision not independently resolved, so excluded from the four verified papers'}],
  'unselected':['LoopSplat discovery query was not developed into a verified primary reading.','Under-review OpenReview results are not treated as accepted papers.'],
  'deduplication':'Bounded rg of work/S23_innovation_*/sources.json: selected4 titles not found; VGGT was found and avoided. This is not proof the project never read a selected title.',
  'novelty_boundary':'Four selected works provide a four-axis positioning exercise. New 2026 search leads are not resolved into a complete closest-prior survey; absence of an exact match cannot certify originality.'},
 'skills_applied':{
  'supervisor_commit':'207bc6f7a1aa107e544099c2c7cc86816fba9628',
  'handbook_2_2':['baseline-to-concrete-failure reasoning','component swaps, same-view/compute controls, ablative attribution'],
  'handbook_2_3':['hidden-assumption probes: staticness, uniform confidence, representation-consumer equivalence','importance and technology-cycle questions; no disruptive claim'],
  'idea_evaluator':['F1/F9 audit before candidate score','three actual mechanism keyword groups; four verified paper comparisons','mechanism-based scores only, no invented measured gains','student lifecycle/compute limitations; lack of hours recorded as unknown','conditional test versus rejected current method proposal'],
  'claude_scientific_critical_thinking':['causation versus association','controls for extra input, training, filtering, camera intrinsics and diffusion randomness','construct validity: geometry/pose/context/video are different outcomes','independent scene unit; previously seen TUM is exploratory'],
  'application_limits':['Not a full literature survey, statistical review or conference-readiness audit.','No Claude model/CLI invocation.','No scientific illustration required for this short textual comparison; no image-generation tool called.']},
 'candidate_audit':{
  'count':1,'positioning':'New-setting question, not an established new mechanism.',
  'hypothesis':'Query direction can change which existing memory geometry disagreements are harmful to actual generation; a single global reliability score may miss that interaction.',
  'two_priority_risks':[{'id':'F1','severity':'UNRESOLVED','detection':'Error propagation, uncertainty weighting and viewpoint selection are already known; setting difference alone does not establish substantive novelty.','response':'Do not claim a method; resolve most proximate generation-selection papers before any method commitment.'},{'id':'F9','severity':'UNRESOLVED','detection':'No project-specific real generated failure has yet motivated this candidate.','response':'First require a natural failure and a discriminating counterfactual with simple strong controls.'}],
  'severity_note':'No arbitrary weeks assigned, no mechanical contradictory MAJOR-count escalation. Untested does not equal data-refuted.',
  'five_dimensions':{'Higher':{'score':5,'basis':'No actual consumer improvement or sufficient causal mechanism evidence.'},'Faster':{'score':5,'basis':'No demonstrated speed claim.'},'Stronger':{'score':6,'basis':'Mechanism-based only: projected geometric disagreements depend on query direction; generation consequence untested.'},'Cheaper':{'score':5,'basis':'No demonstrated cost reduction.'},'Broader':{'score':6,'basis':'Mechanism-based link from reconstruction evidence to generation-context diagnosis; current top-neighbor duplication unresolved.'}},
  'paradigm_probe':{'first_principles':'Partial','elephant_in_room':'No evidence','technology_cycle':'Partial','hamming_importance':'Unproven'},
  'lifecycle_category':'Frontier exploration; no publication timetable asserted','capability':{'weekly_effective_hours':'unknown','student_skill_depth':'beginner self-description; no invented numerical ratings','infrastructure':'M3 Max 64GB, no confirmed remote GPU; original generation runtime readiness owned by root'},
  'verdict':'Reject and Pivot for current method proposal; preserve exactly one falsifiable diagnostic question. No claimed PhD/CCF-A readiness.',
  'falsifiers':['No natural query-dependent ranking reversal under controlled inputs.','Rank changes do not predict actual generated-return consistency.','Global confidence, visible coverage/pose diversity or simple reprojection ranking matches or beats the candidate with matched budget.','Any benefit disappears with common K, source count, history, NMS state and noise.'],
  'research_boundary':'Do not revive S34 ordinary scale/getter repair as innovation; do not infer generated-video gain from geometry metrics. New independent scenes and frozen evaluation are required after exploratory known TUM.'},
 'retrieval_receipts':[str(P/f) for f in ['retrieval_receipt.json','retrieval_fallback_receipt.json','memory_cvpr_retrieval.json','venue_retrieval_receipt.json']],
 'access_failures':'Initial web open 403/internal errors; urllib TLS EOF for several URLs; OpenReview alternate PDF 403. Preserved receipts, successful final PDF identities used.'
}
(D/'sources.json').write_text(json.dumps(source,ensure_ascii=False,indent=2)+'\n')
skillroot=Path('/Users/rocket/Documents/Codex/2026-09-05/users-rocket-desktop-hkust-it-ip/work/Supervisor-Skills/handbook/02_Idea_Generation')
inputs=[ROOT/'AGENTS.md',ROOT/'RESEARCH_PRINCIPLES.md',ROOT/'RESEARCH_MEMORY.md',ROOT/'RESEARCH_LOG.md',ROOT/'vendor/provenance.json',ROOT/'work/S23_supervisor_readthrough/five_route_acceptance.json',Path('/Users/rocket/.codex/skills/idea-evaluator/SKILL.md'),Path('/Users/rocket/.claude/skills/sci-scientific-critical-thinking/SKILL.md'),Path('/Users/rocket/.claude/skills/sci-scientific-critical-thinking/references/experimental_design.md')]
inputs+=list(skillroot.glob('2.2*'))+list(skillroot.glob('2.3*'))
inputs+=[Path('/Users/rocket/.codex/skills/idea-evaluator/references')/f for f in ['fatal-flaws.md','lifecycle-capability-matching.md','five-dimensions.md','paradigm-shift-probe.md']]
assert len(list(skillroot.glob('2.2*')))==1 and len(list(skillroot.glob('2.3*')))==1
receipt={'schema':'s38-b-delivery-v1','recorded_utc':utc(),'status':'BOUNDED_PRIMARY_READING_DELIVERED','author':'/root/research_novelty_routes','scope':'Independent geometry-side paper reading; no external scientific reproduction.','timing':{'first_durable_primary_attempt_utc':records[0]['started_utc'],'primary_access_completed_utc':max(r['ended_utc'] for r in records),'initial_task_start_utc':'not separately recorded; do not fabricate elapsed work hours'},'paper_count':4,'report_han_character_count':len(re.findall('[\u4e00-\u9fff]',(D/'report.md').read_text())),'candidate_count':1,'verified':[{'paper':p['id'],'official_venue_and_year':True,'primary_method_and_key_experiments_read':True} for p in papers],'not_executed':{'model_forward':0,'training':0,'GA':0,'GT_or_scientific_array_reads':0,'Claude_model_or_CLI_calls':0},'scientific_status':'NO_NEW_EXPERIMENTS_OR_METHOD_EFFECT_CLAIM','source_snapshot_identity':[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size} for p in inputs],'scope_limits':['Current code/weights/generation resource acquisition belongs to parent and may advance after this cutoff.','Only selected primary sections were read; supplementary/code and full2026 landscape were not audited.','All file writes in the assigned agent_b_geometry directory; canonical ledger untouched.'],'files':[{'path':str(p.relative_to(D)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(D.rglob('*')) if p.is_file() and p.name!='receipt.json']}
(D/'receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'report_sha256':sha(D/'report.md'),'sources_sha256':sha(D/'sources.json'),'receipt_sha256':sha(D/'receipt.json'),'payload_files':len(receipt['files']),'han_characters':receipt['report_han_character_count'],'recorded_utc':receipt['recorded_utc']},ensure_ascii=False,indent=2))
