"use strict";
(() => {
 const payload=JSON.parse(document.getElementById('payload').textContent), m=payload.meta;
 const $=id=>document.getElementById(id), format=n=>n.toLocaleString('zh-CN');
 function floats(encoded){const binary=atob(encoded), bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const view=new DataView(bytes.buffer),answer=new Float32Array(binary.length/4);for(let i=0;i<answer.length;i++)answer[i]=view.getFloat32(i*4,true);return answer;}
 const xyz=floats(payload.data.points), rgb=floats(payload.data.colors), conf=floats(payload.data.confidence), camR=floats(payload.data.camera_R), camT=floats(payload.data.camera_t);
 const count=m.display_sample_points, per=m.points_per_image;
 if(xyz.length!==count*3||rgb.length!==count*3||conf.length!==count||camR.length!==18||camT.length!==6)throw Error('嵌入数组长度不符，停止显示。');
 $('samplecount').textContent=format(count);$('densecount').textContent=format(m.archived_dense_points);$('provenance').textContent=JSON.stringify(m,null,2);
 $('extent').textContent='完整坐标范围（模型单位，非米）：'+['X','Y','Z'].map((axis,i)=>axis+' '+m.world_bbox_min[i].toPrecision(5)+' … '+m.world_bbox_max[i].toPrecision(5)).join('；');
 const colors=new Array(count);for(let i=0;i<count;i++)colors[i]='rgb('+Math.round(rgb[i*3]*255)+','+Math.round(rgb[i*3+1]*255)+','+Math.round(rgb[i*3+2]*255)+')';
 for(let f=0;f<2;f++){const ctx=$('rgb'+f).getContext('2d'),im=ctx.createImageData(128,96);for(let i=0;i<per;i++){const p=(f*per+i)*3;im.data[i*4]=Math.round(rgb[p]*255);im.data[i*4+1]=Math.round(rgb[p+1]*255);im.data[i*4+2]=Math.round(rgb[p+2]*255);im.data[i*4+3]=255;}ctx.putImageData(im,0,0);$('name'+f).textContent=m.images[f].name;}
 const canvas=$('cloud'),ctx=canvas.getContext('2d'),pos=new Float64Array(count*3),active=[];
 let yaw=0,pitch=0,zoom=1,panX=0,panY=0,frame=0,W=0,H=0,scale=1,dpr=1;
 const center=m.display_center,fitRadius=m.display_fit_radius;
 function rotate(x,y,z){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),a=cy*x+sy*z,c=-sy*x+cy*z;return[a,cp*y-sp*c,sp*y+cp*c];}
 function projected(p){const r=rotate(p[0]-center[0],p[1]-center[1],p[2]-center[2]);return[W/2+panX+r[0]*scale,H/2+panY-r[1]*scale,r[2]];}
 function schedule(){if(!frame)frame=requestAnimationFrame(draw);}
 function updateFilter(){const amount=Number($('confidence').value)/1000,threshold=m.confidence_min+(m.confidence_max-m.confidence_min)*amount;active.length=0;let by=[0,0];for(let i=0;i<count;i++)if(conf[i]>=threshold){active.push(i);by[i<per?0:1]++;}$('threshold').textContent='下限 '+threshold.toPrecision(6)+(amount===0?' · 全部显示':' · 显示筛选已启用');$('shown').textContent='筛选保留 '+format(active.length)+' / '+format(count)+' 点；图0 '+format(by[0])+'，图1 '+format(by[1])+'。视角遮挡与缩放可能使部分点不在屏幕内。';$('accessibleStatus').textContent=$('shown').textContent;schedule();}
 function line(a,b,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();}
 function axes(){const origin=[46,H-47];ctx.font='12px -apple-system,sans-serif';[[1,0,0,'X','#8a3a22'],[0,1,0,'Y','#327147'],[0,0,1,'Z','#005d91']].forEach(v=>{const r=rotate(v[0],v[1],v[2]),end=[origin[0]+r[0]*29,origin[1]-r[1]*29];line(origin,end,v[4],2);ctx.fillStyle=v[4];ctx.fillText(v[3],end[0]+4,end[1]-4);});ctx.fillStyle='#344e5c';ctx.fillText('统一坐标比例 · 任意尺度',12,H-12);}
 function cameras(){for(let f=0;f<2;f++){const p=[camT[f*3],camT[f*3+1],camT[f*3+2]],a=projected(p),length=fitRadius*.08,b=projected([p[0]+camR[f*9+2]*length,p[1]+camR[f*9+5]*length,p[2]+camR[f*9+8]*length]),color=f===0?'#0072b2':'#b24b00';line(a,b,color,2);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(a[0],a[1]-6);ctx.lineTo(a[0]+6,a[1]+5);ctx.lineTo(a[0]-6,a[1]+5);ctx.closePath();ctx.fill();ctx.font='bold 13px -apple-system,sans-serif';ctx.fillText('C'+f,a[0]+8,a[1]-7);}}
 function draw(){frame=0;const rect=canvas.getBoundingClientRect();W=rect.width;H=rect.height;dpr=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#f8fafb';ctx.fillRect(0,0,W,H);scale=.82*Math.min(W,H)/(2*fitRadius)*zoom;const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);for(let n=0;n<active.length;n++){const i=active[n],o=i*3,x=xyz[o]-center[0],y=xyz[o+1]-center[1],z=xyz[o+2]-center[2],a=cy*x+sy*z,c=-sy*x+cy*z;pos[o]=W/2+panX+a*scale;pos[o+1]=H/2+panY-(cp*y-sp*c)*scale;pos[o+2]=sp*y+cp*c;}const order=active.slice().sort((a,b)=>pos[a*3+2]-pos[b*3+2]||a-b),size=Number($('size').value),source=$('colorMode').value==='source';for(const i of order){const x=pos[i*3],y=pos[i*3+1];if(x< -size||x>W+size||y< -size||y>H+size)continue;ctx.fillStyle=source?(i<per?'#0072b2':'#b24b00'):colors[i];if(source&&i<per){ctx.beginPath();ctx.arc(x,y,size*.65,0,Math.PI*2);ctx.fill();}else ctx.fillRect(x-size/2,y-size/2,size,size);}if($('cameras').checked)cameras();axes();}
 function reset(){yaw=0;pitch=0;zoom=1;panX=panY=0;$('confidence').value=0;$('colorMode').value='rgb';$('size').value=2;$('cameras').checked=true;updateFilter();}
 const pointers=new Map();let gesture=null;
 function gestureNow(){const p=[...pointers.values()];return p.length>=2?{distance:Math.max(1,Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y)),x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}:null;}
 canvas.addEventListener('pointerdown',e=>{canvas.focus();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});gesture=gestureNow();});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){const next=gestureNow();if(gesture){zoom=Math.max(.05,Math.min(40,zoom*next.distance/gesture.distance));panX+=next.x-gesture.x;panY+=next.y-gesture.y;}gesture=next;}else if(e.shiftKey){panX+=e.clientX-old.x;panY+=e.clientY-old.y;}else{yaw+=(e.clientX-old.x)*.007;pitch=Math.max(-Math.PI/2,Math.min(Math.PI/2,pitch+(e.clientY-old.y)*.007));}schedule();});
 for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{pointers.delete(e.pointerId);gesture=gestureNow();});
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.05,Math.min(40,zoom*Math.exp(-e.deltaY*.001)));schedule();},{passive:false});
 canvas.addEventListener('keydown',e=>{let handled=true;if(e.key==='ArrowLeft')yaw-=.07;else if(e.key==='ArrowRight')yaw+=.07;else if(e.key==='ArrowUp')pitch=Math.max(-Math.PI/2,pitch-.07);else if(e.key==='ArrowDown')pitch=Math.min(Math.PI/2,pitch+.07);else if(e.key==='+'||e.key==='=')zoom=Math.min(40,zoom*1.15);else if(e.key==='-')zoom=Math.max(.05,zoom/1.15);else if(e.key==='Home')reset();else handled=false;if(handled){e.preventDefault();schedule();}});
 $('confidence').addEventListener('input',updateFilter);for(const id of ['size','colorMode','cameras'])$(id).addEventListener('input',schedule);$('reset').addEventListener('click',reset);$('fit').addEventListener('click',()=>{zoom=1;panX=panY=0;schedule();});new ResizeObserver(schedule).observe(canvas);updateFilter();
})();
