export PYTHONWARNINGS="ignore"
wandb offline
python -m main +name=infer \
    experiment.tasks=[validation] \
    dataset.validation_multiplier=1 \
    +diffusion_model_path=zeqixiao/worldmem_checkpoints/diffusion_only.ckpt \
    +vae_path=zeqixiao/worldmem_checkpoints/vae_only.ckpt \
    +customized_load=true \
    +seperate_load=true \
    dataset.n_frames=8 \
    dataset.save_dir=data/minecraft \
    +dataset.n_frames_valid=700 \
    +dataset.memory_condition_length=8 \
    +dataset.customized_validation=true \
    +dataset.add_timestamp_embedding=true \
    +algorithm.n_tokens=8 \
    +algorithm.memory_condition_length=8 \
    algorithm.context_frames=600 \
    +algorithm.relative_embedding=true \
    +algorithm.log_video=true \
    +algorithm.add_timestamp_embedding=true
