from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,re
D=Path(__file__).parent; R=Path('/Users/rocket/Desktop/HKUST IT/ip-/geometry-world-modeling')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ident(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p)}
receipts=['fetch_receipt.json','fetch_retry_receipt.json','fetch_final_receipt.json','fetch_supp_retry_receipt.json','fetch_supp_system_receipt.json']
access=[]
for n in receipts:
 data=json.loads((D/n).read_text());access.extend(data if isinstance(data,list) else [data])
def source(n):
 p=D/'materials'/n
 successful=[r for r in access if (r.get('name')==n or (n=='streamingt2v_supp.pdf' and r.get('url','').endswith('supplemental.pdf'))) and r.get('sha256')==sha(p)]
 a=successful[-1]
 return {**ident(p),'url':a['url'],'access_started_utc':a['started_utc'],'access_completed_utc':a['completed_utc'],'http_status':a.get('status',a.get('http_status'))}
papers=[
 {'id':'streamingt2v','title':'StreamingT2V: Consistent, Dynamic, and Extendable Long Video Generation from Text','authors':['Roberto Henschel','Levon Khachatryan','Hayk Poghosyan','Daniil Hayrapetyan','Vahram Tadevosyan','Zhangyang Wang','Shant Navasardyan','Humphrey Shi'],'year':2025,'venue':'CVPR 2025 main conference','pages':'2568-2577','venue_evidence':'CVF official accepted-version statement and InProceedings booktitle/year','read_scope':{'main':'Sections 4.1-4.3 and 5.1-5.2; raw-text lines 275-580, mainly PDF pp.4-7','supplement':'A.3.1/A.3.1.1, A.3.2/A.3.2.1, A.3.3 and A.4 training paragraphs; raw-text lines129-350','not_read':'Complete appendix prompt list, all qualitative figures, all references, source implementation; not a full-paper line-by-line attestation'},'decisive_ablation':'A.3 isolates CAM against Add-Cond/Conc-Cond; A.3.2 compares CAM with/without APM. A.3.3 isolates blending from shared noise.','fairness_limit':'Same initial clip and same dataset in respective comparisons do not establish identical model capacity, training or end-to-end compute. APM fixed initial generated chunk is not inherently real ground truth.','transfer_failure':'Identity metrics are not 3D revisit truth; unseen regions, real dynamic changes, and untrained module insertion can defeat transfer.'},
 {'id':'vmem','title':'VMem: Consistent Interactive Video Scene Generation with Surfel-Indexed View Memory','authors':['Runjia Li','Philip Torr','Andrea Vedaldi','Tomas Jakab'],'year':2025,'venue':'ICCV 2025 main conference','pages':'25690-25699','venue_evidence':'CVF official proceedings author/title/booktitle/year, PDF ICCV watermark','read_scope':{'main':'Sections2 relevant mechanism contrast; 3.1-3.2;4.1-4.4 and Tables1/4; raw-text lines195-600 and605-745','not_read':'Full supplement; not a new complete code audit'},'decisive_ablation':'Table4 compares temporal/camera-distance/FOV/surfel retrieval inside each fixed K group. Table1 explicitly has identical short-horizon K17 outputs when context fits.','fairness_limit':'K4 vs K17 includes fine-tuned backbone/total frame count differences; 12x is not solely index acceleration. Fixed-K retrieval ablation is the more relevant mechanism comparison.','transfer_failure':'Geometry change may leave actual ordered conditions unchanged; generator can still fail after correct retrieval.'},
 {'id':'worldmem','title':'WorldMem: Long-term Consistent World Simulation with Memory','authors':['Zeqi Xiao','Yushi Lan','Yifan Zhou','Wenqi Ouyang','Shuai Yang','Yanhong Zeng','Xingang Pan'],'year':2025,'venue':'NeurIPS 2025 main conference','volume':38,'venue_evidence':'Official NeurIPS proceedings main-conference page and exact linked proceedings PDF','read_scope':{'main':'Sections3.1-3.4,4.1-4.2,5; Algorithm1, equations3-6, Tables1-6; raw-text lines206-568, PDF pp.4-10','not_read':'Full appended checklist, all auxiliary videos or authors code'},'decisive_ablation':'Table2 separates dense/relative pose encoding; Table3 separates confidence and similarity retrieval; Table6 tests time condition on placed-object events.','fairness_limit':'Memory model obtains extra historical frames; Minecraft quantitative protocols use given simulator poses. Within-window self-consistency target and beyond-window real future targets are different constructs.','transfer_failure':'Noisy poses/occlusion can undermine retrieval; static TUM windows cannot verify dynamic state evolution.'},
 {'id':'longlive','title':'LongLive: Real-time Interactive Long Video Generation','authors':['Shuai Yang','Wei Huang','Ruihang Chu','Yicheng Xiao','Yuyang Zhao','Xianbang Wang','Muyang Li','Enze Xie','Yingcong Chen','Yao Lu','Song Han','Yukang Chen'],'year':2026,'venue':'ICLR 2026 conference','venue_evidence':'Official ICLR2026 proceedings page and linked accepted paper header','read_scope':{'main':'Sections3.1-3.3 and4.1-4.5; Tables1-4/Fig7; raw-text lines197-530; PDF pp.3-9','appendix':'Algorithm2 tail and F.1 implementation/training, raw-text850-920; no exhaustive appendix read','visual':'Actually viewed local PDF page8 PNG to resolve Table4 caption versus cells','not_read':'Full author code, all appendix figures or demo videos'},'decisive_ablation':'Table4 clear/retain/recache at a5s switch in a10s video; Figure7 fixed effective-window comparison9local+3sink vs12local.','fairness_limit':'Extra recache/training costs remain; 32GPU-days and H100 FPS are author hardware results, not our CPU measurements.','caption_table_conflict':{'source':'Table4, PDFp8','caption_claim':'recache best consistency and CLIP','actual_clip_cells':{'no_kv_cache':28.95,'retained_kv_cache':25.92,'kv_recache':27.87},'interpretation':'Recache improves trade-off versus retained cache; do not claim best CLIP among all three. PDF raster actually checked.'},'transfer_failure':'Original VMem has different cross-call state; its cached producer latent is not the same object as LongLive causal KV. Training-free transplantation is unsupported.'}
]
for p in papers:
 p['formal_paper']=source(p['id']+'.pdf');p['official_venue']=source(p['id']+'_venue.html');p['text_extraction']=ident(D/'materials'/(p['id']+'.txt'))
 if p['id']=='streamingt2v':p['supplement']=source('streamingt2v_supp.pdf');p['supplement_text']=ident(D/'materials/streamingt2v_supp.txt')
local_reads={
 R/'AGENTS.md':'full',R/'RESEARCH_PRINCIPLES.md':'full current v1.5',R/'RESEARCH_MEMORY.md':'full current summary/relevant S34-S38 boundary; current mutable file',R/'RESEARCH_LOG.md':'newest approximately11000 characters through actual access grant at03:08:50UTC',R/'docs/S37_RESUMPTION.md':'full; superseded account-status facts checked against latest log',R/'work/S23_innovation_3_generation/idea.md':'full core hypothesis/nearest works/experiment and boundaries; approximately first14500 characters in latest turn plus earlier established reading',R/'work/S23_innovation_3_generation/sources.json':'prior neighbor identities, used as navigation not current venue certification',R/'work/S20_environment/isolated_vmem_source/modeling/pipeline.py':'lines1120-1240; actual get_cond mean and separated crossattn/replace/rays. No execution',
 Path('/Users/rocket/.codex/skills/idea-evaluator/SKILL.md'):'full',Path('/Users/rocket/.codex/skills/idea-evaluator/references/fatal-flaws.md'):'full',Path('/Users/rocket/.codex/skills/idea-evaluator/references/lifecycle-capability-matching.md'):'lines1-100',Path('/Users/rocket/.codex/skills/idea-evaluator/references/five-dimensions.md'):'lines1-100; existing scoring discipline from full entrypoint',Path('/Users/rocket/.codex/skills/idea-evaluator/references/paradigm-shift-probe.md'):'lines1-105',Path('/Users/rocket/.claude/skills/sci-scientific-critical-thinking/SKILL.md'):'full; applied construct validity, confounding, proportionality',R/'work/S23_innovation_3_generation/sources/handbook_2_2.md':'full pinned prior saved handbook copy',R/'work/S23_innovation_3_generation/sources/handbook_2_3.md':'full pinned prior saved handbook copy',Path('/Users/rocket/.codex/memories/MEMORY.md'):'initial registry search and lines326-360; historical navigation only, current science/resource facts checked in project'
}
novelty={
 'type':'New Setting / falsifiable diagnostic, not validated new method','question':'Can geometry-retrieved references harm return-view appearance through their pooled semantic direction, conditional on identical ordered latents, cameras and selected information?',
 'status':'UNTESTED; NOT PREREGISTERED; NOT AUTHORIZED AS A SCIENTIFIC RUN BY THIS DOCUMENT',
 'source_fact':'Original get_cond averages selected CLIP encoder_embeddings on dim0 at1125 and repeats at1150. Producer latent replace and ray/camera conditioning are separate unchanged paths.',
 'interventions':['Original selected-vector mean','A selected previously observed anchor vector, scaled to the norm of the original mean','The selected nearest-camera vector, scaled to the norm of the original mean'],
 'input_gates':['All selected contexts and cached quantities come from original real generation; no fake latent','Anchor must already be in lawful selected set; otherwise retain preselected unit as ineligible/NA without expanding information','Nonzero finite norms and unchanged unconditional inputs; failure means intervention unidentifiable, not a positive result','Same parameters, resolution, steps, noise, pose/intrinsics, latent bytes and ordered contexts; change semantic direction only'],
 'minimal_design':'Only after actual original baseline passes: at least two preselected new physical scenes with paired preset seeds; one natural return request per unit and three matched sampling calls. Exact scene/seed count, joint acceptance margin and runtime cap must be frozen before outputs; no current sample-size/power claim.',
 'endpoints':'Same-view observed-content reconstruction plus requested-view adherence; never treat constant copied frames as success. Report all units and missing reasons; not solely CLIP or geometry error.',
 'baseline_interpretation':'Anchor and nearest-vector routes are ordinary strong controls. If either solves the effect, stop at baseline hardening; no new name or novelty claim.',
 'stop_conditions':['Original full resources or execution gate absent => not testable','No natural eligible exposure => do not force a failure or alter candidate-count rules','No stable paired gain across scenes/seeds or camera adherence worsens => reject benefit version or report uncertainty under frozen margins','Effects require altered norm, additional frames, GT-based choice, changed focal/latents or post-hoc selection => causal claim invalid','Ordinary anchor/nearest control explains benefit => reject novel-method positioning'],
 'closest_axes':[
 {'work':'StreamingT2V','object':'learned anchor appearance guidance versus original VMem existing pooled vector','mechanism':'trained APM versus a diagnostic direction replacement','granularity':'video-chunk anchor tokens versus one pooled selected-set vector','setting':'T2V long identity versus camera-controlled observed revisit'},
 {'work':'VMem','object':'surfel-selected multiview conditions versus their separate semantic pooling path','mechanism':'visibility retrieval versus holding retrieval fixed','granularity':'reference-view set versus one downstream semantic vector','setting':'same original consumer, diagnostic only'},
 {'work':'WorldMem','object':'pose/time-aware token memory versus current consumer semantic vector','mechanism':'learned state-relative attention versus no new training','granularity':'memory tokens/states versus matched pooled direction','setting':'dynamic simulation versus static observed-content revisit'},
 {'work':'LongLive','object':'prompt-conditioned causal KV versus explicit producer latent/CLIP inputs','mechanism':'recache+training versus route-isolation test','granularity':'layer KV versus crossattn input','setting':'prompt switch versus fixed-camera request; not a direct transplantation'}],
 'idea_evaluator':{
  'verdict':'Accept with Revisions for diagnostic only; reject fixed-anchor/weighted-average-as-novel-method framing',
  'fatal_flaws':[{'id':'F6','severity':'MAJOR','finding':'No genuine full-generator failure yet, so geometry/metadata proxy cannot verify semantic harm','defense':'Actual baseline then matched real condition intervention'},{'id':'F1','severity':'MINOR for diagnostic; fatal for proposed anchor-only novelty','finding':'Anchor appearance preservation and state/cache correction already covered','defense':'Do not claim a new method; current bounded search does not establish novelty'}],
  'lifecycle':'Frontier exploration; short-to-medium as handbook category, no promised completion date','capability':'MSc beginner, M3Max64GiB, no remoteGPU, effective weekly hours unknown; four-model full execution still unverified. Full paper training resources do not fit current local premise.',
  'five_dimensions_mechanism_only':{'Higher':{'score':5,'reason':'No measured gain; ordinary anchor may explain it'},'Faster':{'score':4,'reason':'Three paired sampling routes add diagnostic cost; no speedup mechanism'},'Stronger':{'score':6,'reason':'Separating conflicting geometry/semantic conditioning is testable with invariant other inputs, not confirmed'},'Cheaper':{'score':5,'reason':'No new training labels, but generation cost remains unmeasured'},'Broader':{'score':5,'reason':'Source-specific path; no cross-model validation'}},
  'paradigm_probe':{'first_principles':'Partial: downstream semantic use need not track geometry coverage','elephant':'No: long-horizon drift is already studied','technology_cycle':'Partial: full raw consumer observation is newly ready locally, not a field-wide breakthrough','hamming':'No established major effect'},
  'risks':{'compute':'High until original real run measured','data':'Medium; two new scenes insufficient for final confirmation','engineering':'Medium; immutable cache/RNG/condition identity must hold','timeline':'Unknown, not assigned invented student hours'},
  'integrity':'No empirical effect sizes, novelty, PhD level, significance, or resource success inferred from this idea score.'
 },
 's23_nonduplication':'Does not propose branch-ancestry mixing, metadata label interventions, new memory quotas, or scale sweeps. It interrogates a downstream source-proven semantic pathway while holding its reference set fixed.'
}
obj={'schema':'s38-focused-paper-learning-a-v1','recorded_utc':datetime.now(timezone.utc).isoformat(),'scope':'Four formally published selected papers; primary method and ablation reading, not exhaustive survey, replication or claimed state-of-the-art ranking','papers':papers,'source_access_receipts':receipts,'web_discovery':{'queries':['WorldMem official proceedings','StreamingT2V CVPR2025','LongLive ICLR2026','VMem ICCV2025','StreamingT2V A.3.2 APM','video generation CLIP reference averaging consistency memory','view synthesis semantic reference selection memory generation'],'actual_clocked_windows_utc':['2026-09-07 03:12:41–03:12:45','2026-09-07 03:13:32–03:13:35','2026-09-07 03:13:55–03:13:57','2026-09-07 03:19:05–03:19:06','2026-09-07 03:19:27–03:19:30','2026-09-07 03:22:03–03:22:09'],'timing_limit':'First discovery and one cached-supplement open did not capture separate exact tool timestamps; no exact time invented. Every selected primary source has precise successful direct-access start/end above.','unused':'Search snippets/secondary sites were not used for method numbers. Under-review results were not counted as accepted papers.','failures':'Web tool encountered CVF403, largePDF limits and arXivHTML failure; directpublic paper fetching succeeded as receipts show. No credential, TLS verification disabling or paywall bypass.'},'supervisor':{'commit':'207bc6f7a1aa107e544099c2c7cc86816fba9628','2.2':'Existing strong baseline -> actual failure -> mechanism-specific control; stop scale proxy sweep','2.3':'First-principles consumer purpose and opposite-control tradeoffs generated the one question; no paradigm-shift claim'},'claude_skill':'Local scientific-critical-thinking only; no Claude model/CLI; Mermaid used for own conceptual workflow, no artificial scientific results','local_read_snapshot':[dict(ident(p),read_scope=scope) for p,scope in local_reads.items()],'snapshot_caveat':'Local hashes are the receipt-time snapshot of read files; mutable root ledgers may have changed since initial reading or after this seal. Original frozen scientific results unchanged.','candidate':novelty,'artifact_identities':[ident(D/'report.md'),ident(D/'materials/longlive_page8.png'),ident(D/'materials/streamingt2v_page6.png')],'limitations':['Paper values are author-reported, not reproduced','Different data/information/compute regimes prevent cross-paper ranking','Only two extracted paper pages viewed; no full qualitative-video verification','pdftotext repaired a LongLive PDF xref warning; Table4 visually checked against PDF raster','All4 venue/title/year pairs independently verified from official archived pages; no preprint counted as accepted']}
(D/'sources.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
allfiles=[p for p in D.rglob('*') if p.is_file() and p.name!='receipt.json']
receipt={'schema':'s38-paper-learning-delivery-a-v1','status':'COMPLETE_FOUR_PRIMARY_PAPER_LEARNING_ONLY','recorded_utc':datetime.now(timezone.utc).isoformat(),'agent':'/root/innovation_geometry_state','first_direct_fetch_utc':access[0]['started_utc'],'last_direct_fetch_completed_utc':max(a['completed_utc'] for a in access),'start_time_limit':'Earlier mandatory local reads and initial web discovery precede first direct fetch; their exact start was not separately recorded. Duration is not student labor or paper-reading time.','papers_formal':4,'supplements_read':1,'candidate_hypotheses':1,'report_cjk_characters':len(re.findall(r'[\u4e00-\u9fff]',(D/'report.md').read_text())),'direct_http_attempts':len(access),'successful_saved_http_payloads':sum('sha256' in a for a in access),'successful_http_bytes':sum(a.get('bytes',0) for a in access),'direct_failure_count':sum('sha256' not in a for a in access),'files':len(allfiles),'identities':{str(p.relative_to(D)):sha(p) for p in allfiles},'visual_read':{'longlive_page8':'Actually viewed; Table4 numeric trade-off versus caption confirmed','streamingt2v_page6':'Actually viewed; equation6 and Table1; not full figure-quality audit'},'source_and_science_boundaries':{'new_models':0,'new_training_or_optimization':0,'GT_reads':0,'real_prediction_NPZ_reads':0,'model_weight_downloads':0,'canonical_ledger_writes':0,'Claude_model_calls':0,'paper_and_venue_files_only':True},'scientific_status':'NO_NEW_EMPIRICAL_RESULT','novelty_status':'UNVERIFIED; ordinary anchor/gate/averaging not innovation','next':'Parent review focused learning and decide only after original real baseline prerequisites; do not execute candidate from this receipt.'}
(D/'receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
for n in ['report.md','sources.json','receipt.json']:print(n,sha(D/n))
print('paper count',len(papers),'characters',receipt['report_cjk_characters'],'direct attempts',len(access),'savedbytes',receipt['successful_http_bytes'])
